AWSTemplateFormatVersion: "2010-09-09"

Description: This is the main template to spin up a Qumulo Cluster in an existing VPC.  It calls subordinate CloudFormation templates to instantiate the infrastructure.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: AWS Template Configuration
        Parameters:
          - S3BucketName
          - S3KeyPrefix
          - KeyPair
          - SecretsManagedPolicy
          - EnvType

      - Label: 
          default: AWS Network Configuration
        Parameters:
          - VPCId
          - QSgCidr
          - PrivateSubnetID
          - QPublicMgmt
          - PublicSubnetID
          - DomainName
          - QFloatRecordName

      - Label:
          default: Qumulo File Data Platform Configuration
        Parameters:
          - QAmiID
          - QInstanceType
          - QNodeCount
          - QDiskConfig
          - QClusterName
          - QFloatingIP
          - VolumesEncryptionKey
          - QInstanceRecoveryTopic
          - ProvisioningServerAMI

      - Label:
          default: Qumulo CloudWatch Metrics & Monitoring Configuration
        Parameters:
          - SideCarUsername
          - SideCarPassword
          - SideCarTemplate
          - SideCarSNSTopic

    ParameterLabels:
      S3BucketName:
        default: "MANDATORY: Quick Start S3 Bucket Name"
      S3KeyPrefix:
        default: "MANDATORY: Quick Start S3 Key Prefix Name"
      KeyPair:
        default: "MANDATORY: AWS Key-Pair Name"
      SecretsManagedPolicy:
        default: "PREFER DEFAULT: AWS Secrets Managed Policy Name with ARN"
      EnvType:
        default: "OPTIONAL: Environment Type"
      VPCId:
        default: "MANDATORY: AWS VPC ID"
      PrivateSubnetID:
        default: "MANDATORY: AWS Private Subnet ID"
      PublicSubnetID:
        default: "MANDATORY: AWS Public Subnet ID"
      QSgCidr:
        default: "MANDATORY: Qumulo Security Group "
      QPublicMgmt: 
        default: "OPTIONAL: Provision Public IP for Qumulo Management"
      DomainName:
        default: "OPTIONAL: FQDN for R53 Private Hosted Zone"
      QFloatingIP:
        default: "PREFER DEFAULT: Floating IP for IP Failover"
      QFloatRecordName:
        default: "PREFER DEFAULT: R53 Record Name for Qumulo RR DNS "
      QClusterName:
        default: "PREFER DEFAULT: Qumulo Cluster Name"
      QNodeCount: 
        default: "MANDATORY: Number of Qumulo EC2 Instances"
      QDiskConfig:
        default: "MANDATORY: EBS Volume Configuration per EC2 Instance"
      QAmiID:
        default: "MANDATORY: Qumulo AWS AMI ID"
      QInstanceType:
        default: "MANDATORY: Qumulo EC2 Instance Type"
      VolumesEncryptionKey:
        default: "OPTIONAL: AWS EBS Volumes Encryption Key "
      QInstanceRecoveryTopic:
        default: "OPTIONAL: Qumulo Instance Recovery Topic"
      ProvisioningServerAMI:
        default: "PREFER DEFAULT: Linux Server for Secondary Configuration of Qumulo "
      SideCarTemplate:
        default: "PREFER DEFAULT: Qumulo Sidecar Template URL "
      SideCarUsername:
        default: "PREFER DEFAULT: Qumulo Sidecar Username "
      SideCarPassword:
        default: "MANDATORY: Qumulo Sidecar Password "
      SideCarSNSTopic:
        default: "OPTIONAL: Qumulo Sidecar SNS Topic "

Parameters:

  S3BucketName: 
    ConstraintDescription: >-
      CloudFormation assets bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-)
    Description: >-
      S3 bucket name for the CloudFormation assets. The bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
    Default: mys3bucket

  S3KeyPrefix:
    ConstraintDescription: >-
      CloudFormation assets key prefix can include numbers, lowercase letters,
      uppercase letters, and hyphens (-).
    Description: >-
      S3 key prefix for the CloudFormation assets. The key prefix can include numbers,
      lowercase letters, uppercase letters, and hyphens (-).
    Type: String
    Default: QCFT

  KeyPair:
    Description: Name of an existing EC2 Key Pair to enable authentication to instances
    Type: AWS::EC2::KeyPair::KeyName
    Default: mykeypair

  SecretsManagedPolicy:
    Description: Name of an existing Secrets Managed Policy. Default is AWS Policy.
    Type: String
    Default: "arn:aws:iam::aws:policy/SecretsManagerReadWrite"

  EnvType:
    Description: "Type of Environment: Dev, QA, or, Prod"
    AllowedValues:
      - dev
      - qa
      - prod
    Type: String
    Default: dev

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: AWS VPC ID.

  QPublicMgmt:
    AllowedValues:
      - "YES"
      - "NO"
    Description: Select YES to provision an Elastic IP Address (public static) attached to a Network Loadbalancer listening only on port 443 for Qumulo Managment.
    Type: String
    Default: "NO"

  PublicSubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: IGNORED if NO Public Management is selected above. However, an AWS subnet ID must be selected regardless.

  PrivateSubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: AWS Private Subnet in the VPC.

  DomainName:
    Description: "IF NONE.local, R53 config will be skipped. Private R53 DNS Fully Qualified Domain Name.  The .local domain is one way to provide public query resolution for overlapping names: qumulo.com vs qumulo.local"
    AllowedPattern: '[a-zA-Z0-9]+\..+'
    MaxLength: '255'
    MinLength: '2'
    Type: String
    Default: "NONE.local"  

  QFloatRecordName:
    Description: ONLY APPLICABLE if an domain name was provided above.  Record Name for R53 Private Hosted Zone Qumulo Cluster floating IPs.
    Type: String
    Default: qumulo

  QNodeCount:
    Description: "The number of EC2 instances, or Qumulo Nodes in the Qumulo Cluster: (4-10)."
    AllowedValues:
      - "4"
      - "5"
      - "6"
      - "7"
      - "8"
      - "9"
      - "10"
    Type: String
    Default: "4"

  QDiskConfig:
    Description: "Choose the EBS Volume configuration and type for each Qumulo EC2 instance: AF= SSD, Hybrid st1= SSD+HDD st1, Hybrid sc1= SSD+HDD sc1. NOTE: This must match the EBS capacity and type of the chosen AMI-ID above."
    AllowedValues:
      - 600GiB-AF
      - 1TB-AF
      - 5TB-AF
      - 8TiB-AF
      - 13TiB-AF
      - 20TiB-AF
      - 30TB-AF
      - 35TiB-AF
      - 55TiB-AF
      - 5TB-Hybrid-st1
      - 8TiB-Hybrid-st1
      - 13TiB-Hybrid-st1
      - 20TB-Hybrid-st1
      - 35TiB-Hybrid-st1
      - 55TiB-Hybrid-st1
      - 90TiB-Hybrid-st1
      - 160TiB-Hybrid-st1
      - 256TiB-Hybrid-st1
      - 320TiB-Hybrid-st1
      - 8TiB-Hybrid-sc1
      - 13TiB-Hybrid-sc1
      - 20TB-Hybrid-sc1
      - 35TiB-Hybrid-sc1
      - 55TiB-Hybrid-sc1
      - 90TiB-Hybrid-sc1
      - 160TiB-Hybrid-sc1
      - 256TiB-Hybrid-sc1
      - 320TiB-Hybrid-sc1
    Type: String
    Default: 600GiB-AF

  QAmiID:
    Description: "AWS Amazon Machine Image ID, ami-xxxxxxxxxxxxxxxxx, default AMI is for 600GiB AF in us-west-2. Qumulo AMI-IDs are unique per config and per region."
    Type: AWS::EC2::Image::Id
    Default: "ami-0f00e2f69ba43a7c1"

  QFloatingIP:
    AllowedValues:
      - "1"
      - "2"
      - "3"
      - "4"
    Description: "Number of EC2 Secondary IPs to be configured for each instance in the cluster, 1-4"
    Type: String
    Default: "3"

  QClusterName:
    AllowedPattern: "^[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]$"
    Description: Name must be an alpha-numeric string between 2 and 15 characters. Dash (-) is allowed if not the first or last character.
    MaxLength: 15
    MinLength: 2
    Type: String
    Default: Cloud-Q

  QInstanceType:
    AllowedValues:
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - m5.12xlarge
      - m5.16xlarge
      - m5.24xlarge
      - c5n.9xlarge
      - c5n.18xlarge
    Description: "EC2 instance type for Qumulo nodes." 
    Type: String
    Default: "m5.2xlarge"

  VolumesEncryptionKey: 
    Description: "Leave Blank and AWS will generate a key. To specify a Customer Managed Key provide the KMS CMK ID: 12345678-1234-1234-1234-1234567890ab"
    Type: String
    Default: ""

  QInstanceRecoveryTopic:
    Description: Optionally enter the ARN of an SNS topic that receives messages when an instance alarm is triggered.
    Type: String
    Default: ""

  QSgCidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(3[0-2]|[1-2][0-9]|[0-9]))$"
    Description: An IPv4 CIDR block for specifying the generated security group's allowed addresses for inbound traffic. Set to the VPC CIDR.
    Type: String
    Default: "172.31.0.0/16"

  ProvisioningServerAMI: 
    Description: AWS Linux Server AMI
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"

  SideCarTemplate:
    Description: Do not change this unless newer version of Qumulo is being used for the AMI-ID provided.
    Type: String
    Default: "https://qumulo-sidecar-us-east-1.s3.amazonaws.com/3.3.0/sidecar_cft.json"

  SideCarUsername:
    Type: String
    Default: SideCarUser

  SideCarPassword:
    AllowedPattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*[@$!%*?&\\-_])[A-Za-z\\d@$!%*?&\\-_]{8,}$"
    Description: "Minumum 8 characters and must include one each of: uppercase, lowercase, and a special character."
    MaxLength: 128
    MinLength: 8
    Type: String
    Default: secuRe_pwd4
    NoEcho: "true"

  SideCarSNSTopic:
    Description: Optionally enter an SNS topic ARN that lambda errors and successful disk replacements will be published to.
    Type: String
    Default: ""

Conditions:
  ProvR53: !Not
    - !Equals
      - !Ref DomainName
      - "NONE.local"

  ProvMgmt: !Not
    - !Equals
      - !Ref QPublicMgmt
      - "NO"
  
Resources:

  SECRETSSTACK:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        SideCarUsername: !Ref SideCarUsername
        SideCarPassword: !Ref SideCarPassword
      TemplateURL: !Sub "https://${S3BucketName}.s3.${AWS::URLSuffix}/${S3KeyPrefix}/cfn/store-secrets.cft.yaml"
      TimeoutInMinutes: 150      

  QIAMSTACK:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${S3BucketName}.s3.${AWS::URLSuffix}/${S3KeyPrefix}/cfn/qiam.cft.yaml"
      TimeoutInMinutes: 150

  QSTACK:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: QIAMSTACK
    Properties:
      Parameters:
        ClusterName: !Ref QClusterName
        ClusterAMI: !Ref QAmiID
        FloatingIPCount: !Ref QFloatingIP
        IamInstanceProfile: !GetAtt QIAMSTACK.Outputs.QumuloIAMProfile
        InstanceRecoveryTopic: !Ref QInstanceRecoveryTopic
        InstanceType: !Ref QInstanceType
        KeyName: !Ref KeyPair
        SgCidr: !Ref QSgCidr
        SubnetId: !Ref PrivateSubnetID
        VolumesEncryptionKey: !Ref VolumesEncryptionKey
        VpcId: !Ref VPCId
      TemplateURL: !Sub "https://${S3BucketName}.s3.${AWS::URLSuffix}/${S3KeyPrefix}/cfn/cluster-configs/${QNodeCount}x${QDiskConfig}-SA.cft.json"
      TimeoutInMinutes: 150

  QSIDECARSTACK:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: QSTACK
    Properties:
      Parameters:
        SecurityGroup: !GetAtt QSTACK.Outputs.ClusterSGID
        SNSTopic: !Ref SideCarSNSTopic
        Subnet: !Ref PrivateSubnetID
        Username: !Ref SideCarUsername
        Password: !Ref SideCarPassword
        Hosts: !GetAtt QSTACK.Outputs.ClusterPrivateIPs
      TemplateURL: !Ref SideCarTemplate
      TimeoutInMinutes: 150

  PROVISIONINGSTACK:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: QSIDECARSTACK
    Properties:
      Parameters:
        ProvisioningServerAMI: !Ref ProvisioningServerAMI
        SecretsManagedPolicy: !Ref SecretsManagedPolicy
        KeyName: !Ref KeyPair
        Region: !Ref AWS::Region
        PrivateSubnetId: !Ref PrivateSubnetID
        PrivateSubnetCidr: !Ref QSgCidr
        Node1IP: !Select [0, !Split [", ", !GetAtt QSTACK.Outputs.ClusterPrivateIPs]]
        FloatIPs: !GetAtt QSTACK.Outputs.ClusterSecondaryPrivateIPs
        InstanceIDs: !GetAtt QSTACK.Outputs.ClusterInstanceIDs
        ClusterPwd: !GetAtt QSTACK.Outputs.TemporaryPassword
        VPCID: !Ref VPCId
        SideCarSecretsArn: !GetAtt SECRETSSTACK.Outputs.SideCarSecretsArn
        CMK: !Ref VolumesEncryptionKey
        StackName: !Ref AWS::StackName
        QStackName: !GetAtt QSTACK.Outputs.AWSStackName
        CMKPolicyPath: !Sub "${S3BucketName}/${S3KeyPrefix}"   
        BucketName: !Ref S3BucketName
      TemplateURL: !Sub "https://${S3BucketName}.s3.${AWS::URLSuffix}/${S3KeyPrefix}/cfn/provisioning-node-nodc.cft.yaml" 
      TimeoutInMinutes: 150

  CLOUDWATCHSTACK:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: PROVISIONINGSTACK
    Properties:
      Parameters:
        QStackID: !GetAtt QSTACK.Outputs.AWSStackID
        QStackName: !GetAtt QSTACK.Outputs.AWSStackName
        TopStackName: !Ref AWS::StackName
        AllFlash: !Select [1, !Split ["-", !Ref QDiskConfig]]
      TemplateURL: !Sub "https://${S3BucketName}.s3.${AWS::URLSuffix}/${S3KeyPrefix}/cfn/resource-group.cft.yaml"

  DNSSTACK:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: PROVISIONINGSTACK
    Condition: ProvR53
    Properties:
      Parameters:
        FQDName: !Ref DomainName
        VPCId: !Ref VPCId
        Region: !Ref AWS::Region
        FloatIPs: !GetAtt QSTACK.Outputs.ClusterSecondaryPrivateIPs
        NumNodes: !Ref QNodeCount
        NumIPs: !Ref QFloatingIP
        RecordName: !Ref QFloatRecordName
      TemplateURL: !Sub "https://${S3BucketName}.s3.${AWS::URLSuffix}/${S3KeyPrefix}/cfn/r53-private-zone.cft.yaml"
      TimeoutInMinutes: 150

  MGMTNLBSTACK:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: PROVISIONINGSTACK
    Condition: ProvMgmt
    Properties:
      Parameters:
        VPCID: !Ref VPCId
        PublicSubnetID: !Ref PublicSubnetID
        NodeIPs: !GetAtt QSTACK.Outputs.ClusterPrivateIPs
        NumNodes: !Ref QNodeCount
      TemplateURL: !Sub "https://${S3BucketName}.s3.${AWS::URLSuffix}/${S3KeyPrefix}/cfn/mgmt-nlb.cft.yaml"
      TimeoutInMinutes: 150

Outputs:

  QumuloPrivateIP:
    Description: Private IP for Qumulo Cluster Management
    Value: !If
      - ProvR53
      - !Join
        - ""
        - - "https://"
          - !GetAtt DNSSTACK.Outputs.ClusterDNS
      - !GetAtt QSTACK.Outputs.LinkToManagement
  QumuloPublicIP:
    Condition: ProvMgmt
    Description: Public IP for Qumulo Cluster Management
    Value: !GetAtt MGMTNLBSTACK.Outputs.ManagementEIP
  QumuloTempPassword:
    Description: Temporary Password for Qumulo Cluster
    Value: !GetAtt QSTACK.Outputs.TemporaryPassword
  QumuloPrivateDNSName:
    Condition: ProvR53
    Description: Private DNS Name for Qumulo Cluster
    Value: !GetAtt DNSSTACK.Outputs.ClusterDNS
  QumuloKnowledgeBase:
    Description: Qumulo Knowledge Base
    Value: !GetAtt QSTACK.Outputs.QumuloKnowledgeBase
    



