AWSTemplateFormatVersion: "2010-09-09"

# MIT License
#
# Copyright (c) 2021 Qumulo, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal 
# in the Software without restriction, including without limitation the rights 
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell 
# copies of the Software, and to permit persons to whom the Software is 
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
# SOFTWARE.

Description: This is the main template to spin up a Qumulo Cluster in an existing VPC.  It calls subordinate CloudFormation templates to instantiate the infrastructure.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: AWS Template Configuration - aws-sa-waf-cluster version 2.4
        Parameters:
          - S3BucketName
          - S3KeyPrefix
          - S3BucketRegion
          - KeyPair
          - EnvType

      - Label: 
          default: AWS Network Configuration
        Parameters:
          - VPCId
          - QSgCidr
          - PrivateSubnetID
          - QClusterLocalZone
          - SideCarPrivateSubnetID
          - QPublicMgmt
          - QPublicRepl
          - PublicSubnetID
          - DomainName
          - QFloatRecordName

      - Label:
          default: Qumulo File Data Platform Configuration
        Parameters:
          - QAmiID
          - QInstanceType
          - QNodeCount
          - QDiskConfig
          - QClusterVersion
          - QClusterName
          - QClusterAdminPwd
          - QFloatingIP
          - VolumesEncryptionKey
          - QInstanceRecoveryTopic
          - ProvisioningServerAMI

      - Label:
          default: Qumulo CloudWatch Metrics & Monitoring Configuration
        Parameters:
          - SideCarUsername
          - SideCarPassword
          - SideCarVersion
          - SideCarSNSTopic

    ParameterLabels:
      S3BucketName:
        default: "S3 Bucket Name"
      S3KeyPrefix:
        default: "S3 Key Prefix Name (Path in the bucket inclusive of aws-sa-waf-cluster folder)"
      S3BucketRegion:
        default: "S3 Bucket Region"
      KeyPair:
        default: "AWS Key-Pair Name"
      EnvType:
        default: "OPTIONAL: Environment Type"
      VPCId:
        default: "AWS VPC ID"
      PrivateSubnetID:
        default: "AWS Private Subnet ID"
      PublicSubnetID:
        default: "AWS Public Subnet ID"
      QSgCidr:
        default: "Qumulo Security Group "
      QPublicMgmt: 
        default: "OPTIONAL: Provision Public IP for Qumulo Management"
      QPublicRepl: 
        default: "OPTIONAL: Enable Replication Port for Qumulo Public IP"        
      DomainName:
        default: "OPTIONAL: FQDN for R53 Private Hosted Zone"
      QFloatingIP:
        default: "Floating IP for IP Failover"
      QFloatRecordName:
        default: "R53 Record Name for Qumulo RR DNS "
      QClusterName:
        default: "Qumulo Cluster Name"
      QClusterAdminPwd:
        default: "Qumulo Cluster Admin Password"
      QNodeCount: 
        default: "Number of Qumulo EC2 Instances"
      QDiskConfig:
        default: "EBS Volume Configuration per EC2 Instance"
      QClusterVersion:
        default: "Qumulo Core Software Version"
      QAmiID:
        default: "Qumulo AWS AMI ID"
      QInstanceType:
        default: "Qumulo EC2 Instance Type"
      VolumesEncryptionKey:
        default: "OPTIONAL: AWS EBS Volumes Encryption Key "
      QInstanceRecoveryTopic:
        default: "OPTIONAL: Qumulo Instance Recovery Topic"
      ProvisioningServerAMI:
        default: "Linux Server for Secondary Configuration of Qumulo "
      QClusterLocalZone:
        default: "Is the Qumulo Cluster being deployed in a Local Zone?"
      SideCarPrivateSubnetID:
        default: "Qumulo Sidecar Lambdas Private Subnet ID"
      SideCarVersion:
        default: "Qumulo Sidecar Software Version "
      SideCarUsername:
        default: "Qumulo Sidecar Username "
      SideCarPassword:
        default: "Qumulo Sidecar Password "
      SideCarSNSTopic:
        default: "OPTIONAL: Qumulo Sidecar SNS Topic "

Parameters:

  S3BucketName: 
    ConstraintDescription: >-
      CloudFormation assets bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-)
    Description: >-
      S3 bucket name for the CloudFormation assets. The bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
    Default: mys3bucket

  S3KeyPrefix:
    ConstraintDescription: >-
      CloudFormation assets key prefix can include numbers, lowercase letters,
      uppercase letters, and hyphens (-).
    Description: >-
      S3 key prefix for the CloudFormation assets. The key prefix can include numbers,
      lowercase letters, uppercase letters, hyphens (-), and a final /.
    Type: String
    Default: aws-sa-waf-cluster/

  S3BucketRegion:
    Description: 'AWS Region where the CloudFormation assets S3 bucket is 
    hosted. This is NOT necessarily the same region the CloudFormation template is being executed in.'
    Type: String
    Default: 'us-west-2'

  KeyPair:
    Description: Name of an existing EC2 Key Pair to enable authentication to instances
    Type: AWS::EC2::KeyPair::KeyName
    Default: mykeypair

  EnvType:
    Description: "Type of Environment: Dev, QA, or, Prod"
    AllowedValues:
      - dev
      - qa
      - prod
    Type: String
    Default: dev

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: AWS VPC ID.

  QPublicMgmt:
    AllowedValues:
      - "YES"
      - "NO"
    Description: Select YES to provision an Elastic IP Address (public static) attached to a Network Loadbalancer listening only on port 443 for Qumulo Managment.  Not supported in Local Zones.
    Type: String
    Default: "NO"

  QPublicRepl:
    AllowedValues:
      - "YES"
      - "NO"
    Description: Select YES to enable port 3712 for replication from on-prem Qumulo systems using the Elastic IP (public static) for Qumulo Managment.  Requires YES to Public Management above.
    Type: String
    Default: "NO"

  PublicSubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: An AWS subnet ID must be selected regardless of the choice above but is only used if YES is chosen above.

  PrivateSubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: AWS Private Subnet in the VPC.

  DomainName:
    Description: "IF NONE.local, R53 config will be skipped. Private R53 DNS Fully Qualified Domain Name.  The .local domain is one way to provide public query resolution for overlapping names: qumulo.com vs qumulo.local"
    AllowedPattern: '[a-zA-Z0-9]+\..+'
    MaxLength: '255'
    MinLength: '2'
    Type: String
    Default: "NONE.local"  

  QFloatRecordName:
    Description: ONLY APPLICABLE if an domain name was provided above.  Record Name for R53 Private Hosted Zone Qumulo Cluster floating IPs.
    Type: String
    Default: qumulo

  QNodeCount:
    Description: "The number of EC2 instances, or Qumulo Nodes in the Qumulo Cluster: (4-10).  NOTE: This field may be used to add nodes with a CloudFormation Stack Update after initial provisioning."
    AllowedValues:
      - "4"
      - "5"
      - "6"
      - "7"
      - "8"
      - "9"
      - "10"
    Type: String
    Default: "4"

  QDiskConfig:
    Description: "Choose the EBS Volume configuration and type for each Qumulo EC2 instance: AF= SSD, Hybrid st1= SSD+HDD st1, Hybrid sc1= SSD+HDD sc1. NOTE: This must match the EBS capacity and type of the chosen AMI-ID above."
    AllowedValues:
      - 600GiB-AF
      - 1TB-AF
      - 5TB-AF
      - 8TiB-AF
      - 13TiB-AF
      - 20TiB-AF
      - 30TB-AF
      - 35TiB-AF
      - 55TiB-AF
      - 5TB-Hybrid-st1
      - 8TiB-Hybrid-st1
      - 13TiB-Hybrid-st1
      - 20TB-Hybrid-st1
      - 35TiB-Hybrid-st1
      - 55TiB-Hybrid-st1
      - 90TiB-Hybrid-st1
      - 160TiB-Hybrid-st1
      - 256TiB-Hybrid-st1
      - 320TiB-Hybrid-st1
      - 8TiB-Hybrid-sc1
      - 13TiB-Hybrid-sc1
      - 20TB-Hybrid-sc1
      - 35TiB-Hybrid-sc1
      - 55TiB-Hybrid-sc1
      - 90TiB-Hybrid-sc1
      - 160TiB-Hybrid-sc1
      - 256TiB-Hybrid-sc1
      - 320TiB-Hybrid-sc1
    Type: String
    Default: 600GiB-AF

  QAmiID:
    Description: "AWS Amazon Machine Image ID, ami-xxxxxxxxxxxxxxxxx, default AMI is for 600GiB AF in us-west-2, 1TB Usable. Qumulo AMI-IDs are unique per config and per region."
    Type: AWS::EC2::Image::Id
    Default: "ami-0df4d523885a06ad2"

  QFloatingIP:
    AllowedValues:
      - "1"
      - "2"
      - "3"
      - "4"
    Description: "Number of EC2 Secondary IPs to be configured for each instance in the cluster, 1-4"
    Type: String
    Default: "3"

  QClusterName:
    AllowedPattern: "^[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]$"
    Description: Name must be an alpha-numeric string between 2 and 15 characters. Dash (-) is allowed if not the first or last character.
    MaxLength: 15
    MinLength: 2
    Type: String
    Default: Cloud-Q

  QClusterVersion:
    Description: "Software version to install on the cluster.  NOTE: This field CAN NOT be used to upgrade the cluster with a CloudFormation Stack Update.
                 All Updates after initial creation must follow the quarterly release cadence using the Web UI or REST API."
    MaxLength: 11
    MinLength: 5
    Type: String
    Default: "4.1.0"

  QClusterAdminPwd:
    AllowedPattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*[@$!%*?&\\-_])[A-Za-z\\d@$!%*?&\\-_]{8,}$"
    Description: "Minumum 8 characters and must include one each of: uppercase, lowercase, and a special character."
    MaxLength: 128
    MinLength: 8
    Type: String
    NoEcho: "true"

  QInstanceType:
    AllowedValues:
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - m5.12xlarge
      - m5.16xlarge
      - m5.24xlarge
      - c5n.4xlarge
      - c5n.9xlarge
      - c5n.18xlarge
    Description: "EC2 instance type for Qumulo nodes." 
    Type: String
    Default: "m5.2xlarge"

  VolumesEncryptionKey: 
    Description: "Leave Blank and AWS will generate a key. To specify a Customer Managed Key provide the KMS CMK ID: 12345678-1234-1234-1234-1234567890ab"
    Type: String
    Default: ""

  QInstanceRecoveryTopic:
    Description: Optionally enter the ARN of an SNS topic that receives messages when an instance alarm is triggered.
    Type: String
    Default: ""

  QSgCidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(3[0-2]|[1-2][0-9]|[0-9]))$"
    Description: An IPv4 CIDR block for specifying the generated security group's allowed addresses for inbound traffic. Set to the VPC CIDR.
    Type: String
    Default: "172.31.0.0/16"

  ProvisioningServerAMI: 
    Description: AWS Linux Server AMI
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"

  QClusterLocalZone:
    Description: Select YES ONLY if the Qumulo Cluster is being deployed in a Local Zone, because AWS Lambda services are not supported in Local Zones, e.g. LA AZs for us-west-2.
    AllowedValues:
      - "YES"
      - "NO"
    Type: String
    Default: "NO"

  SideCarPrivateSubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: "An AWS subnet ID must be selected regardless of the choice above but is only used if YES is chosen above.
                 IF YES for Local Zone above, then select a subnet in one of the region's AZs that is NOT a Local Zone. 
                 NOTE, AWS routetables will need to support inter-AZ traffic so the Sidecar Lambdas can communicate with the cluster"

  SideCarVersion:
    Description: "Software Version should match the desired cluster version at creation.  NOTE: This field may be used to upgrade the SideCar software version 
                  with a CloudFormation Stack Update after upgrading the cluster via the Web UI or REST API."
    MaxLength: 11
    MinLength: 5
    Type: String
    Default: "4.1.0"

  SideCarUsername:
    Type: String
    Default: SideCarUser

  SideCarPassword:
    AllowedPattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*[@$!%*?&\\-_])[A-Za-z\\d@$!%*?&\\-_]{8,}$"
    Description: "Minumum 8 characters and must include one each of: uppercase, lowercase, and a special character."
    MaxLength: 128
    MinLength: 8
    Type: String
    Default: secuRe_pwd4
    NoEcho: "true"

  SideCarSNSTopic:
    Description: Optionally enter an SNS topic ARN that lambda errors and successful disk replacements will be published to.
    Type: String
    Default: ""

Conditions:
  ProvR53: !Not
    - !Equals
      - !Ref DomainName
      - "NONE.local"

  PubMgmt: !Not
    - !Equals
      - !Ref QPublicMgmt
      - "NO"

  LocalAZ: !Not
    - !Equals
      - !Ref QClusterLocalZone
      - "NO"

  ProvMgmt: !And [Condition: PubMgmt, !Not [Condition: LocalAZ]]
  
Resources:

  SECRETSSTACK:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        SideCarUsername: !Ref SideCarUsername
        SideCarPassword: !Ref SideCarPassword
        ClusterAdminPwd: !Ref QClusterAdminPwd
      TemplateURL: !Sub "https://${S3BucketName}.s3.${AWS::URLSuffix}/${S3KeyPrefix}cfn/store-secrets.cft.yaml"
      TimeoutInMinutes: 150      

  QIAMSTACK:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${S3BucketName}.s3.${AWS::URLSuffix}/${S3KeyPrefix}cfn/qiam.cft.yaml"
      TimeoutInMinutes: 150

  QSTACK:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: QIAMSTACK
    Properties:
      Parameters:
        ClusterName: !Ref QClusterName
        ClusterAMI: !Ref QAmiID
        FloatingIPCount: !Ref QFloatingIP
        IamInstanceProfile: !GetAtt QIAMSTACK.Outputs.QumuloIAMProfile
        InstanceRecoveryTopic: !Ref QInstanceRecoveryTopic
        InstanceType: !Ref QInstanceType
        KeyName: !Ref KeyPair
        SgCidr: !Ref QSgCidr
        SubnetId: !Ref PrivateSubnetID
        VolumesEncryptionKey: !Ref VolumesEncryptionKey
        VpcId: !Ref VPCId
      TemplateURL: !Sub "https://${S3BucketName}.s3.${AWS::URLSuffix}/${S3KeyPrefix}cfn/cluster-configs/${QNodeCount}x${QDiskConfig}-SA.cft.json"
      TimeoutInMinutes: 150

  QSIDECARSTACK:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: QSTACK
    Properties:
      Parameters:
        SecurityGroup: !GetAtt QSTACK.Outputs.ClusterSGID
        SNSTopic: !Ref SideCarSNSTopic
        Subnet: !If [LocalAZ, !Ref SideCarPrivateSubnetID, !Ref PrivateSubnetID]
        Username: !Ref SideCarUsername
        Password: !Ref SideCarPassword
        Hosts: !GetAtt QSTACK.Outputs.ClusterPrivateIPs
      TemplateURL: !Sub "https://qumulo-sidecar-us-east-1.s3.amazonaws.com/${SideCarVersion}/sidecar_cft.json"
      TimeoutInMinutes: 150

  MGMTNLBSTACK:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: QSTACK
    Condition: ProvMgmt
    Properties:
      Parameters:
        VPCID: !Ref VPCId
        PublicSubnetID: !Ref PublicSubnetID
        NodeIPs: !GetAtt QSTACK.Outputs.ClusterPrivateIPs
        NumNodes: !Ref QNodeCount
        EnableReplication: !Ref QPublicRepl
      TemplateURL: !Sub "https://${S3BucketName}.s3.${AWS::URLSuffix}/${S3KeyPrefix}cfn/mgmt-nlb.cft.yaml"
      TimeoutInMinutes: 150

  PROVISIONINGSTACK:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: QSIDECARSTACK
    Properties:
      Parameters:
        ProvisioningServerAMI: !Ref ProvisioningServerAMI
        SecretsManagedPolicy: "arn:aws:iam::aws:policy/SecretsManagerReadWrite"
        KeyName: !Ref KeyPair
        Region: !Ref AWS::Region
        PrivateSubnetId: !Ref PrivateSubnetID
        PrivateSubnetCidr: !Ref QSgCidr
        Node1IP: !Select [0, !Split [", ", !GetAtt QSTACK.Outputs.ClusterPrivateIPs]]
        NodeIPs: !GetAtt QSTACK.Outputs.ClusterPrivateIPs
        FloatIPs: !GetAtt QSTACK.Outputs.ClusterSecondaryPrivateIPs
        InstanceIDs: !GetAtt QSTACK.Outputs.ClusterInstanceIDs
        ClusterPwd: !GetAtt QSTACK.Outputs.TemporaryPassword
        VPCID: !Ref VPCId
        SideCarSecretsArn: !GetAtt SECRETSSTACK.Outputs.SideCarSecretsArn
        ClusterSecretsArn: !GetAtt SECRETSSTACK.Outputs.ClusterSecretsArn
        SoftwareSecretsArn: !GetAtt SECRETSSTACK.Outputs.SoftwareSecretsArn
        CMK: !Ref VolumesEncryptionKey
        StackName: !Ref AWS::StackName
        QStackName: !GetAtt QSTACK.Outputs.AWSStackName
        QClusterName: !Ref QClusterName  
        QClusterVersion: !Ref QClusterVersion
        BucketName: !Ref S3BucketName
        KeyPrefix: !Ref S3KeyPrefix
        BucketRegion: !Ref S3BucketRegion
      TemplateURL: !Sub "https://${S3BucketName}.s3.${AWS::URLSuffix}/${S3KeyPrefix}cfn/provisioning-node-nodc.cft.yaml" 
      TimeoutInMinutes: 150

  CLOUDWATCHSTACK:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: PROVISIONINGSTACK
    Properties:
      Parameters:
        QStackID: !GetAtt QSTACK.Outputs.AWSStackID
        QStackName: !GetAtt QSTACK.Outputs.AWSStackName
        TopStackName: !Ref AWS::StackName
        AllFlash: !Select [1, !Split ["-", !Ref QDiskConfig]]
      TemplateURL: !Sub "https://${S3BucketName}.s3.${AWS::URLSuffix}/${S3KeyPrefix}cfn/resource-group.cft.yaml"

  DNSSTACK:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: PROVISIONINGSTACK
    Condition: ProvR53
    Properties:
      Parameters:
        FQDName: !Ref DomainName
        VPCId: !Ref VPCId
        Region: !Ref AWS::Region
        FloatIPs: !GetAtt QSTACK.Outputs.ClusterSecondaryPrivateIPs
        NumNodes: !Ref QNodeCount
        NumIPs: !Ref QFloatingIP
        RecordName: !Ref QFloatRecordName
      TemplateURL: !Sub "https://${S3BucketName}.s3.${AWS::URLSuffix}/${S3KeyPrefix}cfn/r53-private-zone.cft.yaml"
      TimeoutInMinutes: 150

Outputs:

  QumuloPrivateIP:
    Description: Private IP for Qumulo Cluster Management
    Value: !If
      - ProvR53
      - !Join
        - ""
        - - "https://"
          - !GetAtt DNSSTACK.Outputs.ClusterDNS
      - !GetAtt QSTACK.Outputs.LinkToManagement
  QumuloPublicIP:
    Condition: ProvMgmt
    Description: Public IP for Qumulo Cluster Management and Replication
    Value: !GetAtt MGMTNLBSTACK.Outputs.ManagementEIP
  QumuloPrivateDNSName:
    Condition: ProvR53
    Description: Private DNS Name for Qumulo Cluster
    Value: !GetAtt DNSSTACK.Outputs.ClusterDNS
  QumuloKnowledgeBase:
    Description: Qumulo Knowledge Base
    Value: !GetAtt QSTACK.Outputs.QumuloKnowledgeBase
    



