AWSTemplateFormatVersion: "2010-09-09"
Description: This template creates an private hosted zone in R53 DNS

Parameters:
  FQDName:
    Type: String
  VPCId:
    Type: String
  Region:
    Type: String
  FloatIPs: 
    Type: String
  NumNodes:
    Type: String
  NumIPs:
    Type: String
  RecordName:
    Type: String

Conditions:

  Node4:  !Equals [!Ref NumNodes, "4"]
  Node5:  !Equals [!Ref NumNodes, "5"]
  Node6:  !Equals [!Ref NumNodes, "6"]
  Node7:  !Equals [!Ref NumNodes, "7"]
  Node8:  !Equals [!Ref NumNodes, "8"]
  Node9:  !Equals [!Ref NumNodes, "9"]
  Node10: !Equals [!Ref NumNodes, "10"]

  Float1: !Equals [!Ref NumIPs, "1"]
  Float2: !Equals [!Ref NumIPs, "2"]
  Float3: !Equals [!Ref NumIPs, "3"]
  Float4: !Equals [!Ref NumIPs, "4"]

  Provision5:  !Or [!And [Condition: Node5,  Condition: Float1],                                             Condition: Provision6]
  Provision6:  !Or [!And [Condition: Node6,  Condition: Float1],                                             Condition: Provision7]
  Provision7:  !Or [!And [Condition: Node7,  Condition: Float1],                                             Condition: Provision8]
  Provision8:  !Or [!And [Condition: Node8,  Condition: Float1], !And [Condition: Node4, Condition: Float2], Condition: Provision9]
  Provision9:  !Or [!And [Condition: Node9,  Condition: Float1],                                             Condition: Provision10]
  Provision10: !Or [!And [Condition: Node10, Condition: Float1], !And [Condition: Node5, Condition: Float2], Condition: Provision12]
  Provision12: !Or [!And [Condition: Node6,  Condition: Float2], !And [Condition: Node4, Condition: Float3], Condition: Provision14]
  Provision14: !Or [!And [Condition: Node7,  Condition: Float2],                                             Condition: Provision15]
  Provision15: !Or [!And [Condition: Node5,  Condition: Float3],                                             Condition: Provision16]
  Provision16: !Or [!And [Condition: Node8,  Condition: Float2], !And [Condition: Node4, Condition: Float4], Condition: Provision18]
  Provision18: !Or [!And [Condition: Node9,  Condition: Float2], !And [Condition: Node6, Condition: Float3], Condition: Provision20]
  Provision20: !Or [!And [Condition: Node10, Condition: Float2], !And [Condition: Node5, Condition: Float4], Condition: Provision21]
  Provision21: !Or [!And [Condition: Node7,  Condition: Float3],                                             Condition: Provision24]
  Provision24: !Or [!And [Condition: Node8,  Condition: Float3], !And [Condition: Node6, Condition: Float4], Condition: Provision27]
  Provision27: !Or [!And [Condition: Node9,  Condition: Float3],                                             Condition: Provision28]
  Provision28: !Or [!And [Condition: Node7,  Condition: Float4],                                             Condition: Provision30]
  Provision30: !Or [!And [Condition: Node10, Condition: Float3],                                             Condition: Provision32]
  Provision32: !Or [!And [Condition: Node8,  Condition: Float4],                                             Condition: Provision36]
  Provision36: !Or [!And [Condition: Node9,  Condition: Float4],                                             Condition: Provision40]
  Provision40:      !And [Condition: Node10, Condition: Float4]


Resources:
  DNSZone: 
    Type: "AWS::Route53::HostedZone"
    Properties: 
      Name: !Ref FQDName
      VPCs: 
        - 
          VPCId: !Ref VPCId
          VPCRegion: !Ref Region
      HostedZoneTags: 
        - 
          Key: Name
          Value: !Join
            - ""
            - - !Ref "AWS::StackName"
              - " - Hosted Private Zone"
  RoundRobinGroup:
    Type: AWS::Route53::RecordSetGroup
    DependsOn: DNSZone
    Properties:
      Comment: "A Records for DNS RR to Qumulo Cluster Frontend"
      HostedZoneId: !Ref DNSZone
      RecordSets:
        - Name: !Sub "${RecordName}.${FQDName}"
          ResourceRecords: 
            - !Select [0, !Split [", ", !Ref FloatIPs]]
          SetIdentifier: "Qumulo FIP 1"
          Type: A
          TTL: "0"
          Weight: "0"
        - Name: !Sub "${RecordName}.${FQDName}"
          ResourceRecords: 
            - !Select [1, !Split [", ", !Ref FloatIPs]]
          SetIdentifier: "Qumulo FIP 2"
          Type: A
          TTL: "0"
          Weight: "0"
        - Name: !Sub "${RecordName}.${FQDName}"
          ResourceRecords: 
            - !Select [2, !Split [", ", !Ref FloatIPs]]
          SetIdentifier: "Qumulo FIP 3"
          Type: A
          TTL: "0"
          Weight: "0"
        - Name: !Sub "${RecordName}.${FQDName}"
          ResourceRecords: 
            - !Select [3, !Split [", ", !Ref FloatIPs]]
          SetIdentifier: "Qumulo FIP 4"
          Type: A
          TTL: "0"
          Weight: "0"
        - !If
          - Provision5
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [4, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 5"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision6
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [5, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 6"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision7
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [6, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 7"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision8
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [7, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 8"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision9
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [8, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 9"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision10
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [9, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 10"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision12
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [10, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 11"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision12
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [11, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 12"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision14
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [12, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 13"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision14
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [13, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 14"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision15
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [14, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 15"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision16
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [15, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 16"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision18
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [16, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 17"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision18
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [17, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 18"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision20
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [18, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 19"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision20
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [19, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 20"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision21
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [20, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 21"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision24
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [21, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 22"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision24
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [22, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 23"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision24
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [23, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 24"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision27
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [24, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 25"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision27
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [25, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 26"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision27
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [26, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 27"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision28
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [27, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 28"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision30
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [28, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 29"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision30
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [29, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 30"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision32
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [30, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 31"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision32
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [31, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 32"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision36
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [32, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 33"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision36
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [33, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 34"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision36
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [34, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 35"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision36
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [35, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 36"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision40
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [36, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 37"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision40
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [37, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 38"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision40
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [38, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 39"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
        - !If
          - Provision40
          - Name: !Sub "${RecordName}.${FQDName}"
            ResourceRecords: 
              - !Select [39, !Split [", ", !Ref FloatIPs]]
            SetIdentifier: "Qumulo FIP 40"
            Type: A
            TTL: "0"
            Weight: "0"
          - !Ref AWS::NoValue
          
Outputs:
  ClusterDNS:
    Value: !Sub "${RecordName}.${FQDName}"
