AWSTemplateFormatVersion: "2010-09-09"
Description: This template stores Secrets for subsequent use in nested stacks

Parameters:
  SideCarUsername:
    Type: String
  SideCarPassword:
    Type: String
    NoEcho: "True"

Resources:
  SideCarSecrets:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: !Join 
        - ""
        - - !Ref "AWS::StackName"
          - "-SideCarSecrets"
      Description: "Sidecar Lambda function user name and password for Qumulo cluster access"
      SecretString: !Sub '{ "username" : "${SideCarUsername}", "password" : "${SideCarPassword}" }'
Outputs:
  SideCarSecretsArn:
    Value: !Ref SideCarSecrets